require('dotenv').config();
const express=require('express'), session=require('express-session'), bcrypt=require('bcryptjs'), multer=require('multer');
const {Pool}=require('pg'); const PgSession=require('connect-pg-simple')(session);
const app=express(); const upload=multer({storage:multer.memoryStorage(), limits:{fileSize:5*1024*1024}, fileFilter:(req,file,cb)=>{/image\/(jpeg|png|gif|jpg)/.test(file.mimetype)?cb(null,true):cb(new Error('이미지는 JPG, PNG, GIF만 가능합니다.'))}});
const pool=new Pool({connectionString:process.env.DATABASE_URL, ssl:process.env.DATABASE_URL?.includes('supabase')?{rejectUnauthorized:false}:undefined});
const q=(s,p=[])=>pool.query(s,p); const img=f=>f?`data:${f.mimetype};base64,${f.buffer.toString('base64')}`:null;
async function ensureSchema(){await q('ALTER TABLE vendors ADD COLUMN IF NOT EXISTS kakao_url text'); await q(`CREATE TABLE IF NOT EXISTS inquiries(id SERIAL PRIMARY KEY,type text,company_name text,name text,phone text,kakao text,email text,category text,region text,content text,main_image_data text,banner_image_data text,status text DEFAULT 'new',created_at timestamp DEFAULT now())`); await q("ALTER TABLE inquiries ADD COLUMN IF NOT EXISTS banner_status text DEFAULT 'new'");}
app.set('view engine','ejs'); app.use(express.urlencoded({extended:true,limit:'10mb'})); app.use(express.json({limit:'10mb'})); app.use('/public',express.static('public'));
app.use(session({store:new PgSession({pool,createTableIfMissing:true}), secret:process.env.SESSION_SECRET||'dev-secret', resave:false, saveUninitialized:false, cookie:{maxAge:1000*60*60*12}}));
app.use((req,res,next)=>{res.locals.me=req.session.user||null; next();});
function admin(req,res,next){ if(req.session.user?.role==='admin') return next(); res.redirect('/admin/login'); }
function login(req,res,next){ if(req.session.user) return next(); res.redirect('/login'); }
async function homeData(req){ const search=req.query.search||'', region=req.query.region||'', category=req.query.category||''; let where=['status=$1'], p=['active']; if(search){p.push(`%${search}%`); where.push(`(name ILIKE $${p.length} OR tags ILIKE $${p.length} OR description ILIKE $${p.length})`)} if(region){p.push(region); where.push(`region=$${p.length}`)} if(category){p.push(category); where.push(`category=$${p.length}`)} const vendors=await q(`SELECT v.*, (SELECT ROUND(AVG(r.rating)::numeric,1) FROM reviews r WHERE r.vendor_id=v.id AND r.status='visible') avg_rating, (SELECT COUNT(*)::int FROM reviews r WHERE r.vendor_id=v.id AND r.status='visible') review_count FROM vendors v WHERE ${where.join(' AND ')} ORDER BY is_premium DESC,is_recommended DESC,created_at DESC`,p); const banners=await q(`SELECT * FROM banners WHERE is_active=true ORDER BY sort_order, id DESC`); const reviews=await q(`SELECT r.*,v.name vendor_name,u.nickname FROM reviews r LEFT JOIN vendors v ON v.id=r.vendor_id LEFT JOIN users u ON u.id=r.user_id WHERE r.status='visible' ORDER BY r.id DESC LIMIT 8`); const notices=await q(`SELECT * FROM notices ORDER BY is_pinned DESC,id DESC LIMIT 5`); return {vendors:vendors.rows,banners:banners.rows,reviews:reviews.rows,notices:notices.rows,query:req.query}; }
app.get('/',async(req,res)=>res.render('index',await homeData(req)));
app.get('/advertise',(req,res)=>res.render('inquiry',{type:'ad',title:'광고문의',done:false,error:null}));
app.get('/apply',(req,res)=>res.render('inquiry',{type:'apply',title:'입점신청',done:false,error:null}));
app.post('/inquiry',upload.fields([{name:'main_image',maxCount:1},{name:'banner_image',maxCount:1}]),async(req,res)=>{try{const f=req.files||{}; await q('INSERT INTO inquiries(type,company_name,name,phone,kakao,email,category,region,content,main_image_data,banner_image_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[req.body.type,req.body.company_name,req.body.name,req.body.phone,req.body.kakao,req.body.email,req.body.category,req.body.region,req.body.content,img(f.main_image?.[0]),img(f.banner_image?.[0])]); res.render('inquiry',{type:req.body.type,title:req.body.type==='apply'?'입점신청':'광고문의',done:true,error:null});}catch(e){res.render('inquiry',{type:req.body.type||'ad',title:req.body.type==='apply'?'입점신청':'광고문의',done:false,error:e.message||'신청 저장 실패'});}});
async function vendorData(req,id){req.session.viewedVendors=req.session.viewedVendors||{}; if(!req.session.viewedVendors[id]){await q('UPDATE vendors SET views=views+1 WHERE id=$1',[id]); req.session.viewedVendors[id]=Date.now();} const v=await q(`SELECT v.*, (SELECT ROUND(AVG(r.rating)::numeric,1) FROM reviews r WHERE r.vendor_id=v.id AND r.status='visible') avg_rating, (SELECT COUNT(*)::int FROM reviews r WHERE r.vendor_id=v.id AND r.status='visible') review_count FROM vendors v WHERE v.id=$1`,[id]); const reviews=await q('SELECT r.*,u.nickname FROM reviews r LEFT JOIN users u ON u.id=r.user_id WHERE r.vendor_id=$1 AND r.status=$2 ORDER BY r.id DESC',[id,'visible']); return {vendor:v.rows[0],reviews:reviews.rows};}
app.get('/api/vendor/:id',async(req,res)=>{const data=await vendorData(req,req.params.id); if(!data.vendor)return res.status(404).json({error:'not found'}); res.json(data);});
app.post('/api/review',async(req,res)=>{if(!req.session.user)return res.status(401).json({error:'login_required'}); const rating=Math.max(1,Math.min(5,parseInt(req.body.rating||5,10))); await q('INSERT INTO reviews(vendor_id,user_id,title,content,rating) VALUES($1,$2,$3,$4,$5)',[req.body.vendor_id,req.session.user.id,req.body.title,req.body.content,rating]); res.json({ok:true});});
app.get('/vendor/:id',async(req,res)=>{const data=await vendorData(req,req.params.id); if(!data.vendor)return res.status(404).send('Not found'); res.render('vendor',data);});
app.get('/login',(req,res)=>res.render('login',{mode:'login',error:null})); app.post('/login',async(req,res)=>{const u=await q('SELECT * FROM users WHERE username=$1',[req.body.username]); if(!u.rows[0]||u.rows[0].status!=='active'||!await bcrypt.compare(req.body.password,u.rows[0].password_hash)) return res.render('login',{mode:'login',error:'아이디 또는 비밀번호가 올바르지 않습니다.'}); req.session.user={id:u.rows[0].id,username:u.rows[0].username,nickname:u.rows[0].nickname,role:u.rows[0].role}; res.redirect(u.rows[0].role==='admin'?'/admin':'/');});
app.get('/join',(req,res)=>res.render('login',{mode:'join',error:null})); app.post('/join',async(req,res)=>{try{const h=await bcrypt.hash(req.body.password,10); await q('INSERT INTO users(username,password_hash,nickname) VALUES($1,$2,$3)',[req.body.username,h,req.body.nickname||req.body.username]); res.redirect('/login')}catch(e){res.render('login',{mode:'join',error:'이미 사용 중인 아이디입니다.'})}});
app.get('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
app.post('/review',login,async(req,res)=>{await q('INSERT INTO reviews(vendor_id,user_id,title,content,rating) VALUES($1,$2,$3,$4,$5)',[req.body.vendor_id,req.session.user.id,req.body.title,req.body.content,req.body.rating||5]); res.redirect('/vendor/'+req.body.vendor_id);});
app.get('/admin/login',(req,res)=>res.render('admin-login',{error:null})); app.post('/admin/login',async(req,res)=>{const u=await q('SELECT * FROM users WHERE username=$1 AND role=$2',[req.body.username,'admin']); if(!u.rows[0]||!await bcrypt.compare(req.body.password,u.rows[0].password_hash)) return res.render('admin-login',{error:'관리자 로그인 실패'}); req.session.user={id:u.rows[0].id,username:u.rows[0].username,nickname:u.rows[0].nickname,role:'admin'}; res.redirect('/admin');});
app.get('/admin/inquiries',admin,async(req,res)=>{const r=await q('SELECT * FROM inquiries ORDER BY id DESC'); res.render('admin-inquiries',{inquiries:r.rows});});
app.get('/admin/inquiry-image/:id/:kind',admin,async(req,res)=>{const col=req.params.kind==='banner'?'banner_image_data':'main_image_data'; const r=await q(`SELECT ${col} image_data FROM inquiries WHERE id=$1`,[req.params.id]); const data=r.rows[0]?.image_data; if(!data)return res.status(404).send('이미지가 없습니다.'); const m=data.match(/^data:(.+);base64,(.+)$/); if(!m)return res.status(400).send('이미지 형식 오류'); res.setHeader('Content-Type',m[1]); res.send(Buffer.from(m[2],'base64'));});
app.post('/admin/inquiries/:id/approve',admin,async(req,res)=>{const r=await q('SELECT * FROM inquiries WHERE id=$1',[req.params.id]); const x=r.rows[0]; if(!x)return res.redirect('/admin/inquiries'); if(x.type!=='apply')return res.redirect('/admin/inquiries'); await q('INSERT INTO vendors(name,category,region,phone,kakao_url,description,image_data,is_recommended,is_premium,status) VALUES($1,$2,$3,$4,$5,$6,$7,false,false,$8)',[x.company_name,x.category||'기타',x.region||'기타',x.phone,x.kakao,x.content,x.main_image_data,'active']); await q('UPDATE inquiries SET status=$1 WHERE id=$2',['approved',x.id]); res.redirect('/admin/inquiries');});
app.post('/admin/inquiries/:id/banner',admin,async(req,res)=>{const r=await q('SELECT * FROM inquiries WHERE id=$1',[req.params.id]); const x=r.rows[0]; if(!x||!x.banner_image_data||x.banner_status==='approved')return res.redirect('/admin/inquiries'); await q('INSERT INTO banners(title,subtitle,link_url,position,sort_order,is_active,image_data) VALUES($1,$2,$3,$4,$5,$6,$7)',[x.company_name||'입점신청 배너','입점신청으로 등록된 배너','#','premium',0,true,x.banner_image_data]); await q('UPDATE inquiries SET banner_status=$1 WHERE id=$2',['approved',x.id]); res.redirect('/admin/inquiries');});
app.get('/admin',admin,async(req,res)=>{const [users,vendors,banners,reviews,events,notices,inquiries]=await Promise.all([q('SELECT id,username,nickname,role,status,created_at FROM users ORDER BY id DESC'),q('SELECT * FROM vendors ORDER BY id DESC'),q('SELECT * FROM banners ORDER BY sort_order,id DESC'),q('SELECT r.*,v.name vendor_name FROM reviews r LEFT JOIN vendors v ON v.id=r.vendor_id ORDER BY r.id DESC'),q('SELECT * FROM events ORDER BY id DESC'),q('SELECT * FROM notices ORDER BY id DESC'),q('SELECT * FROM inquiries ORDER BY id DESC')]); res.render('admin',{users:users.rows,vendors:vendors.rows,banners:banners.rows,reviews:reviews.rows,events:events.rows,notices:notices.rows,inquiries:inquiries.rows});});
app.post('/admin/vendor',admin,upload.single('image'),async(req,res)=>{let im=img(req.file); if(req.body.id){let p=[req.body.name,req.body.category,req.body.region,req.body.phone,req.body.kakao_url,req.body.tags,req.body.description,req.body.business_hours,!!req.body.is_recommended,!!req.body.is_premium,req.body.status||'active',req.body.id]; await q(`UPDATE vendors SET name=$1,category=$2,region=$3,phone=$4,kakao_url=$5,tags=$6,description=$7,business_hours=$8,is_recommended=$9,is_premium=$10,status=$11 ${im?', image_data=$13':''} WHERE id=$12`, im?[...p,im]:p)} else await q('INSERT INTO vendors(name,category,region,phone,kakao_url,tags,description,business_hours,is_recommended,is_premium,image_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[req.body.name,req.body.category,req.body.region,req.body.phone,req.body.kakao_url,req.body.tags,req.body.description,req.body.business_hours,!!req.body.is_recommended,!!req.body.is_premium,im]); res.redirect('/admin#vendors');});
app.post('/admin/banner',admin,upload.single('image'),async(req,res)=>{const im=img(req.file); await q('INSERT INTO banners(title,subtitle,link_url,position,sort_order,is_active,image_data) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.body.title,req.body.subtitle,req.body.link_url,req.body.position||'premium',req.body.sort_order||0,!!req.body.is_active,im]); res.redirect('/admin#banners');});
app.post('/admin/user',admin,async(req,res)=>{const h=req.body.password?await bcrypt.hash(req.body.password,10):null; if(req.body.id){ if(h) await q('UPDATE users SET nickname=$1,role=$2,status=$3,password_hash=$4 WHERE id=$5',[req.body.nickname,req.body.role,req.body.status,h,req.body.id]); else await q('UPDATE users SET nickname=$1,role=$2,status=$3 WHERE id=$4',[req.body.nickname,req.body.role,req.body.status,req.body.id]); } res.redirect('/admin#users');});
app.post('/admin/notice',admin,async(req,res)=>{await q('INSERT INTO notices(title,content,is_pinned) VALUES($1,$2,$3)',[req.body.title,req.body.content,!!req.body.is_pinned]); res.redirect('/admin#notices');});
app.post('/admin/delete/:table/:id',admin,async(req,res)=>{const allowed={vendors:'vendors',banners:'banners',users:'users',reviews:'reviews',notices:'notices',events:'events',inquiries:'inquiries'}; if(allowed[req.params.table]) await q(`DELETE FROM ${allowed[req.params.table]} WHERE id=$1`,[req.params.id]); res.redirect('/admin');});
const port=process.env.PORT||3000; ensureSchema().then(()=>app.listen(port,()=>console.log('server on '+port))).catch(e=>{console.error(e);process.exit(1)});